### ISSUE TITLE
Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock

### ISSUE THREAD

**Issue by gangsta** [thbe/puppet-icinga#1]
Hi Thomas 
any idea?
![selection_022](https://cloud.githubusercontent.com/assets/9033514/6459256/550e06d4-c18d-11e4-970a-95428762fe0e.png)

Kindly regards Karen

**Comment by thbe** [comment]
Hi Karen,

check if file /var/lib/mysql/mysql.sock exist and if MySQL server is
running. Depending on the distribution, the location of the local socket
may be different. Which distribution do you use?

Regards Thomas

2015-03-03 10:10 GMT+01:00 Karen notifications@github.com:

> Hi Thomas
> any idea?
> [image: selection_022]
> https://cloud.githubusercontent.com/assets/9033514/6459256/550e06d4-c18d-11e4-970a-95428762fe0e.png
> 
> Kindly regards Karen
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thbe/puppet-icinga/issues/1.

## 

Linux ... enjoy the ride!

**Comment by gangsta** [comment]
its run on centos 6.5 in vagrant box .
dependencies of module is included 

with simple input include ::icinga

[root@thruk ~]# cat /var/lib/mysql/mysql.sock
cat: /var/lib/mysql/mysql.sock: No such file or directory

self /var/lib/mysql/ also not exists.

pid file also does not exists.
[root@thruk ~]# ps -elf | grep [m]ysql
[root@thruk ~]# 

servers also not exists 

[root@thruk ~]# service mysql status
mysql: unrecognized service

locate for sure 
[root@thruk ~]# locate mysql.sock
[root@thruk ~]# 

maybe there is some parameters with ::icinga must included ? 

Kindly regards Karen

**Comment by thbe** [comment]
Hi Karen,

you have to enable the server component like this:

class { '::icinga':
  server  => true,
}

Regards Thomas

**Comment by gangsta** [comment]
Hi Thomas 
when im using 
class { '::icinga':
server => true,
}

get some rare output 
==> default: Running provisioner: puppet...
==> default: Running Puppet with ...
==> default: Error: Could not find class icinga::package::server for thruk on node thruk
==> default: Error: Could not find class icinga::package::server for thruk on node thruk

to make some clear view of, you can check my thruk vagrant 
https://github.com/Karen09/vagrant-thruk
Greetings Karen

**Comment by thbe** [comment]
Hi Karen,

a module modification I did wasn't complete (split client and server). I've
update the module and published 0.3.2 to the forge. I had no time to test
it carefully, maybe you've fun to do it. The module itself is still work in
progress. The goal is an Icinga instance running completely on version 2,
but this take some time and I guess, will restrict the OS to RHEL7 or
similar.

Regards Thomas

2015-03-03 11:20 GMT+01:00 Karen notifications@github.com:

> Hi Thomas
> when im using
> class { '::icinga':
> server => true,
> }
> 
> get some rare output
> ==> default: Running provisioner: puppet...
> ==> default: Running Puppet with ...
> ==> default: Error: Could not find class icinga:[image: :package:]:server
> for thruk on node thruk
> ==> default: Error: Could not find class icinga:[image: :package:]:server
> for thruk on node thruk
> 
> to make some clear view of, you can check my trunk vagrant
> https://github.com/Karen09/vagrant-thruk
> Greetings Karen
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thbe/puppet-icinga/issues/1#issuecomment-76920280.

## 

Linux ... enjoy the ride!

**Comment by gangsta** [comment]
Hi Tomas 
Will try to test it ,if its work before you will test it ,will notify you.thanks for collaboration

Greetings Karen

**Comment by gangsta** [comment]
Hi Tomas 
New commit break some stuff (not working httpd,mysql),for dependability push commit before ,i will try tomorrow configure it out and will back notify you.

Greetings Karen

**Comment by thbe** [comment]
Hi Karen,

I'll try to push a new version later today that will fix the current errors
and also add the client functionality to the module. So check tomorrow for
a new version.

Regards Thomas

2015-03-03 14:30 GMT+01:00 Karen notifications@github.com:

> Hi Tomas
> New commit break some stuff (not working httpd,mysql),for dependability
> push commit before ,i will try tomorrow configure it out and will back
> notify you.
> 
> Greetings Karen
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thbe/puppet-icinga/issues/1#issuecomment-76945019.

## 

Linux ... enjoy the ride!

**Comment by gangsta** [comment]
Hi Tomas 
that is great , you are awesome mens, like work with you. that's why i use your modules,cause i know i get my answers from upstream module.
Greetings Karen

**Comment by thbe** [comment]
Hi Karen,

thanks a lot! I've uploaded a new version. At least for the server component, it could be that you need to execute the module twice to get the relevant repositories in place. When I have some more time, I will check the dependency path to get this ordered. But the module itself should now working.

Regards Thomas

**Comment by gangsta** [comment]
Hi Tomas
If you have some time please get on apache cause apache is not more included in module ,after that commit https://github.com/thbe/puppet-icinga/commit/dfe7954aa0dc1a5ca0ef6d49e03b7c89ca709400
Greetings Karen

**Comment by thbe** [comment]
Hi Karen,

checkout master (v0.4.0, should also be on the forge), Apache is now in the server installation, not in the general or client installation anymore. The Icinga module won't use the Puppetlabs Apache module to setup Apache, instead it will simply install Apache itself and put the relevant configuration file to the Apache folder based on the templates inside module. The Puppetlabs Apache module was my first idea to get this done but it turned out that the module is a bit too complex for simple integration.

Regards Thomas

**Comment by gangsta** [comment]
Hi Thomas
sorry for disadvantage its now worked there was some vagrant issue ,now we are able to use perfect working icinga-web, thanks a lot :+1: 
Greetings Karen

**Comment by thbe** [comment]
Hi Karen,

you're welcome! Just for your information, I'm currently discussing the ordering issue with the repository on the Puppet mailing list, I got a hint that I try later when I have some more time. If it work, I'll push a new version via the forge.

Regards Thomas

**Comment by gangsta** [comment]
Hi Thomas 
That is excellent, just writ here that we able use some fresh commits i`ll be notified .
Greetings Karen
